name: potato_notes
description: Official POSP note app
version: 1.5.2+15

environment:
  sdk: '>=2.2.2 <3.0.0'
  # The example interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: '>=1.5.9-pre.270'

dependencies:
  flutter:
    sdk: flutter

  moor_ffi:
  moor:
  json_serializable:
  sqflite:
  path_provider:
  provider:
  streams_channel:
  outline_material_icons:
  community_material_icon:
  flutter_staggered_grid_view:
  photo_view:
  image_picker:
  back_button_interceptor:
  flutter_svg:
  shared_preferences:
  local_auth:
  flutter_secure_storage:
  http:
  jwt_decode:
  intl:
  uuid:
  rich_text_editor:
    git:
      url: https://github.com/namhyun-gu/flutter_rich_text_editor
  spicy_components:
    git: https://github.com/HrX03/SpicyUIComponents
  get_it:
  json_annotation:


dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator:
  build_runner:
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/