name: Dart CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter:stable

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: flutter pub get
    - name: Compile apk
      run: flutter build apk
    - uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: "build/app/outputs/flutter-apk/app-*-release.apk"

